const String baseUrl = 'https://interface.taajeer.com:1027/api';
const String isRegisteredUserEndPoint = '$baseUrl/UserManagement/login';
const String sendOtpEndPoint = '$baseUrl/UserManagement/sendOtp';
const String registerEndPoint = '$baseUrl/UserManagement/register';
const String verifyOtpEndPoint = '$baseUrl/UserManagement/verifyOtp';
const String isUserRegisteredEndPoint = '$baseUrl/UserManagement/login';
const String getManufacturersEndPoint = '$baseUrl/MotorLubeApp/getManufacturers';
String getCarModelsEndPoint(String model) => '$baseUrl/MotorLubeApp/getBrands/$model';
String getUserInfoEndPoint(String phone) => '$baseUrl/UserManagement/user?mobileNumber=$phone';
